### ISSUE TITLE
是否可以自动发布时 向语雀仓库添加更新日志

### ISSUE THREAD

**Issue by arvinxx** [arvinxx/power-yuque#2]
实现思路：
1. release 之后拿到日志信息；
2. 将日志信息通过 Token 发送到某个语雀知识库中；

存在的问题：
1. 通过 API 创建的日志无法进行目录编排；
2. 无法直接创建语雀内部的文件链接

所以暂时先搁置……还是手动在语雀里加日志好了。

**Comment by DiamondYuan** [comment]
> 实现思路：
> 
> 1. release 之后拿到日志信息；
> 2. 将日志信息通过 Token 发送到某个语雀知识库中；
> 
> 存在的问题：
> 
> 1. 通过 API 创建的日志无法进行目录编排；
> 2. 无法直接创建语雀内部的文件链接
> 
> 所以暂时先搁置……还是手动在语雀里加日志好了。

全部目录都用 yuque 编排，全部文章都通过 api 创建就行了。

**Comment by DiamondYuan** [comment]
web clipper 的文档准备这么干。 用 vurpress 搭建页面，顺便用 waque（瓦雀） 同步到 GitHub。

需要注意的点

1. 文档内的多层级目录需要改造  /a/b ->/a_b

2. 图片需要处理

**Comment by arvinxx** [comment]
我之前想把构建产物直接传语雀上。毕竟 Github 对很多人来说下载速度太慢了……这一点似乎暂时做不到吧？
